modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/lzuzi/pick-up-filter/issues/"

[[mods]]
modId="pickupfilter"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/lzuzi/pick-up-filter/"
logoFile="assets/pickupfilter/textures/icon.png"
#credits="" #optional
authors="${mod_authors}"
description="${mod_description}"

[[mixins]]
config="pickupfilter.mixins.json"
client = []
common = ["net.forge.pickupfilter.mixin.ItemEntityMixinForge"]

[[dependencies.pickupfilter]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.pickupfilter]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
