license="GPL-3.0-only"
issueTrackerURL="https://github.com/roaccat/pick-up-filter/issues/"


[[mods]]
modId="pickupfilter"
version="1.0.2"
displayName="Pick Up Filter (PUF)"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/roaccat/pick-up-filter/"
logoFile="assets/pickupfilter/textures/icon.png"
#credits="" #optional
authors="roaccat & zuzi"
description='''Pick Up Filter (PUF) lets you control which items you pick up in Minecraft.'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="pickupfilter.mixins.json"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.pickupfilter]] #optional
# the modid of the dependency
modId="neoforge" #mandatory
# The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
# 'required' requires the mod to exist, 'optional' does not
# 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
type="required" #mandatory
# Optional field describing why the dependency is required or why it is incompatible
# reason="..."
# The version range of the dependency
versionRange="[21.5.75]" #mandatory
# An ordering relationship for the dependency.
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"

# Here's another dependency
[[dependencies.pickupfilter]]
modId="minecraft"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.21.5]"
ordering="NONE"
side="BOTH"
